// import { Inter } from "next/font/google";
import Script from "next/script";
// import "bootstrap/dist/css/bootstrap.css";
import "../../../public/assets/css/dashlite.css?ver=3.0.0";
import "../../../public/assets/css/theme.css?ver=3.0.0";

// const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Login ukm",
  description: "Generated by create next app",
};

export default function LoginLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      {/* <Head>
        <link rel="stylesheet" href="/assets/css/dashlite.css?ver=3.0.0" />
        <link id="skin-default" rel="stylesheet" href="/assets/css/theme.css?ver=3.0.0" />
      </Head> */}
      <body>
        {children}
        {/* <!-- app-root @e --> */}
        {/* <!-- JavaScript --> */}
        <Script src={`${process.env.NEXT_PUBLIC_APP_URL}/assets/js/bundle.js?ver=3.0.0`}></Script>
        <Script src={`${process.env.NEXT_PUBLIC_APP_URL}/assets/js/scripts.js?ver=3.0.0`}></Script>
        <Script src={`${process.env.NEXT_PUBLIC_APP_URL}/assets/js/charts/chart-ecommerce.js?ver=3.0.0`}></Script>
        <Script src={`${process.env.NEXT_PUBLIC_APP_URL}/assets/js/example-sweetalert.js?ver=3.0.0`}></Script>
      </body>
    </html>
  );
}
